name: tantsaha_market
description: "Tantsaha Market - Comparateur de prix agricoles à Madagascar"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  fl_chart: ^0.68.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_riverpod: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
